[package]
name = "slatty-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "slatty"
path = "src/main.rs"

[dependencies]
slatty-core.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
reqwest = { version = "0.13", default-features = false }
chrono = "0.4.45"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
