[package]
name = "slatty-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
reqwest = { version = "0.13", default-features = false, features = ["json", "query", "gzip", "rustls", "charset", "http2"] }
keyring = "4"
rusqlite = { version = "0.40", features = ["bundled"] }
directories = "6"
sha2 = "0.11.0"
md-5 = "0.11.0"
flate2 = "1.1.10"
url = "2.5.8"
chrono = { version = "0.4.45", features = ["serde"] }
nix = { version = "0.31", features = ["process", "signal", "feature"] }
